name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        feature_flags: ["no-default-features", "all-features"]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: fmt
      run: cargo fmt --all -- --check

    - name: build
      run: cargo build --${{matrix.feature_flags}} --verbose

    - name: test
      run: cargo test --${{matrix.feature_flags}} --verbose

    - name: build benchmarks
      run: cargo test --${{matrix.feature_flags}} --benches --no-run --verbose

    - name: clippy
      run: cargo clippy --${{matrix.feature_flags}} -- -D warnings

    - name: docs
      run: cargo doc --${{matrix.feature_flags}} --document-private-items --no-deps

  fuzz-build:
    strategy:
      matrix:
        feature_flags: ["no-default-features", "all-features"]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install cargo-fuzz
      run: cargo install -f cargo-fuzz --all-features

    - name: Install nightly
      run: rustup toolchain install nightly

    - name: Build fuzz tests
      run: cargo +nightly fuzz build --${{matrix.feature_flags}} --verbose
