name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  lint:
    uses: ./.github/workflows/lint.yml

  fuzz:
    uses: ./.github/workflows/fuzz.yml

  # Validate the crate version matches the tag.
  check_version:
    needs: [build, test, lint, fuzz]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check crate version
        run: "[[ \"v$(yq '.package.version' Cargo.toml)\" == \"${{ github.ref_name }}\" ]]"

  # Create a github release
  github_release:
    needs: [build, test, lint, fuzz, check_version]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  # Publish the crate (scoping the secret to only this job)
  publish_crate:
    needs: [build, test, lint, fuzz, github_release]
    permissions:
      contents: write
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs)

      - uses: actions/checkout@v4

      - name: Publish crate
        if: ${{ env.CARGO_REGISTRY_TOKEN != '' }}
        run: cargo publish
