name: test
on:
  workflow_call:
  pull_request:
  push:
    branches: [master]

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        feature_flags: ["no-default-features", "all-features"]

    runs-on: ubuntu-latest
    container:
      image: rust:latest
      env:
        CARGO_HOME: "/cargo/"

    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache cargo dir
        id: cargo-dir
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo
          path: /cargo

      - name: Cache target dir
        id: target-dir
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-target-dir-${{matrix.feature_flags}}-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-target-dir-${{matrix.feature_flags}}
          path: target

      - name: cargo test
        run: cargo test --workspace --${{matrix.feature_flags}} --no-fail-fast
